### ISSUE TITLE
how to use the huggingface: shunk031 / aesthetics-predictor-v2-sac-logos-ava1-l14-linearMSE

### ISSUE THREAD

**Issue by lzg188** [shunk031/simple-aesthetics-predictor#19]
from transformers import AutoTokenizer, AestheticsPredictorV2Linear
got the following error:
Traceback (most recent call last):
  File "/dl/python385/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/dl/python385/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/root/.vscode-server/extensions/ms-python.debugpy-2024.0.0-linux-x64/bundled/libs/debugpy/adapter/../../debugpy/launcher/../../debugpy/__main__.py", line 39, in <module>
    cli.main()
  File "/root/.vscode-server/extensions/ms-python.debugpy-2024.0.0-linux-x64/bundled/libs/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/server/cli.py", line 430, in main
    run()
  File "/root/.vscode-server/extensions/ms-python.debugpy-2024.0.0-linux-x64/bundled/libs/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/server/cli.py", line 284, in run_file
    runpy.run_path(target, run_name="__main__")
  File "/root/.vscode-server/extensions/ms-python.debugpy-2024.0.0-linux-x64/bundled/libs/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 321, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "/root/.vscode-server/extensions/ms-python.debugpy-2024.0.0-linux-x64/bundled/libs/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 135, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/root/.vscode-server/extensions/ms-python.debugpy-2024.0.0-linux-x64/bundled/libs/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 124, in _run_code
    exec(code, run_globals)
  File "/LocalRun/zhiguo.li/linearMSE/main.py", line 1, in <module>
    from transformers import AutoTokenizer, AestheticsPredictorV2Linear
ImportError: cannot import name 'AestheticsPredictorV2Linear' from 'transformers' (/dl/python385/lib/python3.8/site-packages/transformers/__init__.py)

**Comment by shunk031** [comment]
I'm closing this issue, but if there are any problems, please reopen it again.
